---

#
# edit ipcom
#

- name: Edit configuration of ipcom
  hosts: anez_ve2
  gather_facts: false

  # タスク
  tasks:
    - name: send config commands to ipcom
      fujitsu_ipcom_config:
        commands:
          - hostname iida-ve2
      register: output

    - debug:
        var: output
