---

#
# install cliconf and terminal plugin
#

- name: install cliconf and terminal plugin
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    plugins_dir: ~/.ansible/plugins
    cliconf_dir: ~/.ansible/plugins/cliconf
    terminal_dir: ~/.ansible/plugins/terminal
    module_utils_dir: ~/.ansible/plugins/module_utils
    modules_dir: ~/.ansible/plugins/modules
    src_files:
      - fujitsu_ipcom.py
      - fujitsu_sir.py
      - fujitsu_srs.py
    module_files:
      - fujitsu_ipcom_command.py
      - fujitsu_ipcom_config.py
      - fujitsu_ipcom_facts.py
      - fujitsu_sir_command.py
      - fujitsu_sir_config.py
      - fujitsu_sir_facts.py
      - fujitsu_srs_command.py
      - fujitsu_srs_config.py
      - fujitsu_srs_facts.py

  tasks:
    - name: create directories (if necessary)
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ plugins_dir }}"
        - "{{ cliconf_dir }}"
        - "{{ terminal_dir }}"
        - "{{ module_utils_dir }}"
        - "{{ modules_dir }}"

    - name: copy cliconf files
      copy:
        src: "../plugins/cliconf/{{ item }}"
        dest: "{{ cliconf_dir }}"
      loop: "{{ src_files }}"

    - name: copy terminal files
      copy:
        src: "../plugins/terminal/{{ item }}"
        dest: "{{ terminal_dir }}"
      loop: "{{ src_files }}"

    - name: copy module_utils files
      copy:
        src: "../plugins/module_utils/{{ item }}"
        dest: "{{ module_utils_dir }}"
      loop: "{{ src_files }}"

    - name: copy modules files
      copy:
        src: "../plugins/modules/{{ item }}"
        dest: "{{ modules_dir }}"
      loop: "{{ module_files }}"
